[package]
name = "vulkano1"
version = "0.1.0"
authors = ["croraf <vrafaeli@msn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
vulkano = "0.17"
vulkano-shaders = "0.17"
